services:
  nats:
    image: nats:2.10-alpine
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
  timescale:
    image: timescale/timescaledb:latest-pg16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=smultron
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smultron
  redis:
    image: "redis:alpine"
